### ISSUE TITLE
Dependencies for steamos-modeswitch-inhibitor are missing

### ISSUE THREAD

**Issue by castrojo** [CaptSilver/steamos-clear#2]
On a clean install: 

configure: error: Package requirements (xxf86vm xrandr x11 xrender) were not met:

No package 'xxf86vm' found
No package 'xrandr' found
No package 'x11' found
No package 'xrender' found

Fixed this with `swupd bundle-add devpkg-libX11`

**Comment by CaptSilver** [comment]
Added a requirement installation section to resolve this issue.
