### ISSUE TITLE
Dependencies for steamos-compositor are missing

### ISSUE THREAD

**Issue by castrojo** [CaptSilver/steamos-clear#3]
```
configure: error: Package requirements (xxf86vm gl x11 xrender xcomposite SDL_image libudev xext xdamage) were not met:

No package 'gl' found
No package 'SDL_image' found
No package 'libudev' found

```

Doing a `swupd bundle-add devpkg-SDL_image devpkg-systemd` seemed to do the trick for the last two, trying to find a smaller bundle that provides `gl` without needing to install desktop-dev.

**Comment by CaptSilver** [comment]
I have a lot of developer packages installed on my laptop, I haven't tried to resolve these issues from a clean install as of yet. I added your two suggestions thus far. I will look up to see if there is a smaller bundle for the last one later tonight.

**Comment by CaptSilver** [comment]
All dependencies are installed now, however it is set to download desktop-dev which takes a long time to install. I will continue to test for a smaller bundle.
